### ISSUE TITLE
Compiles and runs, but why is intellisense marking it red?

### ISSUE THREAD

**Issue by erikmartinessanches** [microsoft/Xbox-ATG-Samples#28]
I retargeted the solution to toolset v142. VS Enterprise 2019 version 16.7.0. In this project for example the red only appears in debug mode.
![image](https://user-images.githubusercontent.com/4912935/90332517-d430c380-dfbd-11ea-80c3-42aa405fb3ab.png)

**Comment by walbourn** [comment]
Did you upgrade the Windows SDK as well? What version are you using?

Did you do a full clean rebuild?

If I do the same, I see a few warnings in the DirectX Tool Kit in the Windows 10 SDK (19401) because DirectXTK uses ``/Wall`` that I've suppressed in the latest version of the library, but I don't see any other errors.

**Comment by erikmartinessanches** [comment]
Thanks for the reply, it turns out that my errors had to do with Resharper plugin, clearing its cache resolved it.
