### ISSUE TITLE
Prerequisites in readme.md - build tools 149

### ISSUE THREAD

**Issue by jinkobah** [Microsoft/Xbox-ATG-Samples#3]
Hi, I had problems building the SimplePlay3DSpatialSoundUWP audio sample due to "MSB4057: The target 'MarkupCompilePass1' does not exist in the project" against the DirectXTK project.

Finally solved this by installing the 10.0.14393 Windows 10 SDK for Visual Studio Built Tools 2017 15.2 (26530.15). This is not part of the default build tools install.

Please add build tools and versions to the prereqs, and if there's a way to adjust the build tools installer to include the latest version of all required components, that would be great.

**Comment by walbourn** [comment]
As of April 8, 2017, all the projects in this repo were set to use VS 2017 and the Windows 10 Creators Update SDK (15063). That was when the spatial audio samples were added as well. There should be no reason you have to have the older Windows 10 Anniversary Update SDK (14393) installed to build them.

**Comment by jinkobah** [comment]
That pointed me to the issue. Both DirectXTK .vcxproj files reference 14393 as the minimum version:


 <WindowsTargetPlatformMinVersion>10.0.14393.0</WindowsTargetPlatformMinVersion>


________________________________

**Comment by walbourn** [comment]
The minimum version doesn't impact which SDK is used to build. All it should control is the value that ends up in the AppX manifest in the ``<OSMinVersion>`` element.

I have noticed VS 2017 has a quirk of only showing as possible options for the min version which Windows 10 SDK is installed, which I've noted is silly because the SDK isn't used at all for build--it's rather large for something that just provides a version number to a droplist. Still, I suppose there's something else in their validation that could be incorrectly tied to it as well. I'll see if my VM repro shows this issue...

**Comment by jinkobah** [comment]
Thanks! On clean hardware, I observed that  building the vanilla solution failed but changing the minversion to 15063 caused it to succeed. I retract my original statement about the build tools...they were not required.

________________________________

**Comment by walbourn** [comment]
I have left the min version in most of the samples as 14393 as that's a reasonable minimum. The spatial audio samples need 15063, which is why it appears only DirectXTK is set 'wrong'. I'll verify this behavior and write up at least two bugs for the Visual Studio team:

* The minimum version should not be tied in any way to what SDK is installed since it's just metadata

* The minimum version listed in a static library should probably be ignored

**Comment by jinkobah** [comment]
Makes sense. Thanks for the support!

Best,
-Nic B-

Sent from Nine<http://www.9folders.com/> - Please pardon any typos
________________________________

**Comment by V-AMKARL** [comment]
I'm having this same issue. What's the solution? I have windows 10 15063 and Visual Studio Professional 2017. When I try to compile DirectXTK I get "the target "MarkupCompilePass1" does not exist in the project". I couldn't quite follow from the above whether there is a way for me to get past this... :)

**Comment by walbourn** [comment]
I'm still working through the exact repro, but it sounds like you need to install the Universal Windows Platform apps workload (which includes the Windows 10 SDK 15063), the C++ tools for UWP apps optional component, and the Windows 10 SDK 14393 optional component to get it to build currently.

**Comment by V-AMKARL** [comment]
Super – based on the original thread I already tried installing extra build tools with no luck, but I’ll try what you suggest – Thanks!

-Amy

**Comment by jinkobah** [comment]
I actually didn't need the 14393 SDK. I just needed to manually change the min version to 15063 in DirectXTK project properties.

**Comment by walbourn** [comment]
Yes that is another workaround, but a number of samples are using 14393 as the minimum by design because the APIs in them are not strictly 15063 or later only.

**Comment by walbourn** [comment]
Confirmed. Not great behavior, but at least I know what's happening :) Updated the readme.md.

Thanks!
