### ISSUE TITLE
GraphicsMemory object - do MT compatible ?

### ISSUE THREAD

**Issue by DTL2020** [microsoft/Xbox-ATG-Samples#34]
After adding GraphicsMemory files to my project I start to got exceptions (C++ exception in debug build and 0xC00005 in release) when activating multithreading mode. Single threading works OK. Do GraphicsMemory from DirectXTK12 is MT-compatible ?

The usage is simple - for uploading 1 constant buffer into accelerator memory:

  m_graphicsMemory = std::make_unique<GraphicsMemory>(m_D3D12device.Get());
  m_computeHeap = m_graphicsMemory->Allocate((size_t)(4 * 1024));

  SharedGraphicsResource* pUploadHeap = &m_computeHeap;
  SAD_CS_PARAMS* pCBsadCSparams = reinterpret_cast<SAD_CS_PARAMS*> (pUploadHeap->Memory());

'filling memory here'
 
  m_graphicsMemory->Commit(m_computeCommandQueue.Get());

Exception occur in the 'external' application that load this plugin after returning from the function with this sequence.

Unfortunately exception looks like happens in the server-application so remote debug session simply closes without breaking at the point of error.

**Comment by walbourn** [comment]
``GraphicsMemory``  is one instance per device, and it uses a mutex to support allocation from multiple threads. The problem is that are expected to call ``Commit`` once per frame by the main render loop, so calling it from another thread is quite likely to fail. 

> Note that ``SharedGraphicsResource`` is a smart-pointer, so you should use it as: ``SharedGraphicsResource pUploadHeap = m_computeHeap;`` so it maintains proper ref counts. Using it as a raw pointer defeats the purpose of the type;.

If you want to do "upload of resources on another thread", you should create an instance of ``ResourceUploadBatch`` on the loading thread and use that mechanism to schedule uploads. It supports using copy queues and/or compute queues as well. 

https://github.com/microsoft/DirectXTK12/wiki/ResourceUploadBatch
