### ISSUE TITLE
Cant add any file pickers to SimpleSpatialPlaySoundUWP.cpp

### ISSUE THREAD

**Issue by dts350z** [microsoft/Xbox-ATG-Samples#50]
Working with ChatGPT, I spent 3 hours trying to add some sort of file picker to SimpleSpatialPlaySoundUWP.cpp.

Despite very specific and detailed instructions (in both directions) in the end I could not find a file picker method that could be compiled, with the example, without errors.

Adding winrt to the project resulted in a ton of errors (VS2022).

Asking specifically for a UWP solution, that didn't rely on winrt, also did not result in any picker function compiling with the code (tried 3 or 4 iterative variants, feeding the errors back to ChatGPT).

Please consider adding a file picker to this sample project. There doesn't seem to be ANY file pickers used anywhere in the UWP sample code.

The target platform is Windows 10/11 (not Xbox).

**Comment by walbourn** [comment]
Alas, most of the UWP detailed documentation is focused on [C##](https://learn.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers).

As it turns out, I do have some C++/CX and C++/WinRT sample code [here](https://github.com/microsoft/DirectXTK/wiki/WICTextureLoader#windows-store-apps).
