### ISSUE TITLE
Why doesn't DSV need multiple Descriptor?

### ISSUE THREAD

**Issue by LigaLiao** [Microsoft/Xbox-ATG-Samples#8]
`D3D12_DESCRIPTOR_HEAP_DESC rtvHeapDesc = {};
	rtvHeapDesc.NumDescriptors = c_frameCount;
	rtvHeapDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_RTV;
	rtvHeapDesc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
	Engine::ThrowIfFailed(m_d3dDevice->CreateDescriptorHeap(&rtvHeapDesc, IID_PPV_ARGS(&m_rtvHeap)));
	NAME_D3D12_OBJECT(m_rtvHeap);
	m_rtvDescriptorSize = m_d3dDevice->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);

	D3D12_DESCRIPTOR_HEAP_DESC dsvHeapDesc = {};
	dsvHeapDesc.NumDescriptors = 1;
	dsvHeapDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_DSV;
	dsvHeapDesc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
	ThrowIfFailed(m_d3dDevice->CreateDescriptorHeap(&dsvHeapDesc, IID_PPV_ARGS(&m_dsvHeap)));
	NAME_D3D12_OBJECT(m_dsvHeap);
`

rtvHeapDesc.NumDescriptors = c_frameCount;
dsvHeapDesc.NumDescriptors = 1;   why???

**Comment by walbourn** [comment]
The ATG samples are using a variant of the [Direct3D 12 Game VS Templates](https://github.com/walbourn/directx-vs-templates) which are themselves derived from the 'stock' DirectX 12 App UWP template that is included in Visual Studio. As such, the basic structure of the swapchain is the same.

In DirectX 11 swapchains, the 'buffer swapping' of the presentation frames are handled automatically, but in DirectX 12 you have to do it all explicitly. That is once you ``Present`` the frame which queues the frame for presentation to the user once it's both rendered and flipped, you can't resuse that render target until *after* the system has had a chance to actually present it to the 'front buffer' to the user which can typically take a frame or two. Hence the DirectX 12 [DeviceResources](https://github.com/Microsoft/DirectXTK12/wiki/DeviceResources) implementation creates 2 or 3 render target views depending on your desired back-buffer count. At a minimum, you need 2 because you are 'showing' one render target and 'rendering' to the other.

You don't need to do this with depth/stencil buffers because you only need one frame's worth at any given time--the rendering takes place in frame order--, and then when the associated render target is presented, you can safely reuse the depth/stencil buffer immediately since depth/stencil is not part of the ``Present``.

**Comment by LigaLiao** [comment]
Thank you for the detailed answer ！
